-- backup.sql
-- Esquema PostgreSQL derivado de los modelos Sequelize proporcionados.
-- Nota: RequestStatus y UserRole no fueron incluidos en el código recibido
-- completo. Por seguridad, se almacenan como VARCHAR para no inventar valores
-- de ENUM que podrían no coincidir con los enums reales de la aplicación.

BEGIN;

-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'REQUEST_MANAGER',
    "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP WITH TIME ZONE NULL
);

-- ============================================================
-- CLINICS
-- ============================================================
CREATE TABLE IF NOT EXISTS clinics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    nit VARCHAR(50) NOT NULL UNIQUE,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    "responsibleName" VARCHAR(150) NOT NULL,
    "responsibleEmail" VARCHAR(150) NOT NULL,
    "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP WITH TIME ZONE NULL
);

-- ============================================================
-- WAREHOUSES
-- ============================================================
CREATE TABLE IF NOT EXISTS warehouses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    location VARCHAR(255) NOT NULL,
    "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP WITH TIME ZONE NULL
);

-- ============================================================
-- MEDICINES
-- ============================================================
CREATE TABLE IF NOT EXISTS medicines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id INTEGER NOT NULL,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(50) NOT NULL,
    description TEXT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    "unitPrice" DECIMAL(10,2) NOT NULL,
    "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP WITH TIME ZONE NULL,

    CONSTRAINT medicines_stock_nonnegative CHECK (stock >= 0),
    CONSTRAINT medicines_unit_price_nonnegative CHECK ("unitPrice" >= 0),

    CONSTRAINT medicines_warehouse_fk
        FOREIGN KEY (warehouse_id)
        REFERENCES warehouses(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- SUPPLY REQUESTS
-- ============================================================
CREATE TABLE IF NOT EXISTS supply_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id INTEGER NOT NULL,
    warehouse_id INTEGER NOT NULL,
    medicine_id INTEGER NOT NULL,
    created_by_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    notes TEXT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP WITH TIME ZONE NULL,

    CONSTRAINT supply_requests_quantity_positive CHECK (quantity >= 1),

    CONSTRAINT supply_requests_clinic_fk
        FOREIGN KEY (clinic_id)
        REFERENCES clinics(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT supply_requests_warehouse_fk
        FOREIGN KEY (warehouse_id)
        REFERENCES warehouses(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT supply_requests_medicine_fk
        FOREIGN KEY (medicine_id)
        REFERENCES medicines(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT supply_requests_created_by_fk
        FOREIGN KEY (created_by_id)
        REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- ÍNDICES PARA FOREIGN KEYS
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_medicines_warehouse_id
    ON medicines (warehouse_id);

CREATE INDEX IF NOT EXISTS idx_supply_requests_clinic_id
    ON supply_requests (clinic_id);

CREATE INDEX IF NOT EXISTS idx_supply_requests_warehouse_id
    ON supply_requests (warehouse_id);

CREATE INDEX IF NOT EXISTS idx_supply_requests_medicine_id
    ON supply_requests (medicine_id);

CREATE INDEX IF NOT EXISTS idx_supply_requests_created_by_id
    ON supply_requests (created_by_id);

-- ============================================================
-- ÍNDICES ÚTILES PARA SOFT DELETE / CONSULTAS
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_users_deleted
    ON users ("isDeleted");

CREATE INDEX IF NOT EXISTS idx_clinics_deleted
    ON clinics ("isDeleted");

CREATE INDEX IF NOT EXISTS idx_warehouses_deleted
    ON warehouses ("isDeleted");

CREATE INDEX IF NOT EXISTS idx_medicines_deleted
    ON medicines ("isDeleted");

CREATE INDEX IF NOT EXISTS idx_supply_requests_deleted
    ON supply_requests (is_deleted);

COMMIT;

-- ============================================================
-- RELACIONES DEFINIDAS EN models/index.ts
-- ============================================================
-- Clinic 1:N SupplyRequest
-- Warehouse 1:N Medicine
-- Warehouse 1:N SupplyRequest
-- Medicine 1:N SupplyRequest
-- User 1:N SupplyRequest

-- IMPORTANTE:
-- 1. Los hooks beforeDestroy de Sequelize implementan soft delete
--    mediante isDeleted + paranoid/deletedAt. Las FK anteriores no
--    eliminan físicamente registros relacionados.
--
-- 2. Sequelize paranoid normalmente filtra automáticamente por
--    deletedAt IS NULL. isDeleted es un campo adicional de negocio.
--
-- 3. Para que el esquema sea 100% idéntico al proyecto, hacen falta
--    los valores completos de:
--      - RequestStatus
--      - UserRole
--    y el dialecto/configuración exacta de database.js.
--
-- 4. Si la base usa MySQL/MariaDB en lugar de PostgreSQL, este archivo
--    debe adaptarse (IDENTITY, TIMESTAMP WITH TIME ZONE, etc.).
