import bcrypt from 'bcryptjs';
import { envConfig } from '../config/env.js';
import { IPasswordService, PasswordHashResult } from './interfaces/password.service.interface.js';

/**
 * Service responsible for protecting and verifying passwords.
 *
 * Responsibilities:
 * - Generate a cryptographically secure and unique salt per password.
 * - Generate hashes using bcrypt.
 * - Verify passwords via `bcrypt.compare`.
 * - Prevent plain-text passwords from being persisted.
 *
 * @class PasswordService
 *
 * @security
 * Passwords must remain in plain text only for the time necessary
 * to process them. The system must store exclusively the hash generated by bcrypt.
 *
 * The number of bcrypt rounds is obtained from `BCRYPT_ROUNDS`,
 * allowing adjustment of the computational cost of the algorithm via
 * environment configuration.
 */
export class PasswordService implements IPasswordService {
  /**
   * Generates a cryptographically secure salt and a bcrypt hash
   * for the provided password.
   *
   * The salt is generated randomly for each password.
   * Then bcrypt uses this salt together with the configured number of rounds
   * to generate the hash.
   *
   * Using a different salt per password prevents two users
   * with the same password from necessarily producing the same hash.
   *
   * @param {string} password Plain-text password provided
   *                          by the user.
   *
   * @returns {Promise<PasswordHashResult>}
   * Object containing the bcrypt hash and the salt used.
   *
   * @security
   * The plain-text password must not be stored, logged,
   * included in HTTP responses or persisted in any system.
   *
   * `BCRYPT_ROUNDS` determines the computational cost of bcrypt. A higher
   * value increases the time needed to generate and verify hashes,
   * making brute-force attacks harder, although it also increases the
   * computational cost on the server.
   */
  async hash(password: string): Promise<PasswordHashResult> {
    const salt = await bcrypt.genSalt(envConfig.BCRYPT.ROUNDS);
    const hash = await bcrypt.hash(password, salt);

    return { hash, salt };
  }

  /**
   * Verifies whether a password matches a stored bcrypt hash.
   *
   * It is not necessary to provide the salt separately during
   * verification. bcrypt stores inside the hash itself the information
   * needed to perform the comparison, including the salt and the cost
   * used to generate it.
   *
   * Internally `bcrypt.compare` processes the provided password
   * using the parameters contained in the hash and determines whether
   * both credentials match.
   *
   * @param {string} password Password provided during login.
   * @param {string} hash Stored bcrypt hash for the user.
   *
   * @returns {Promise<boolean>}
   * `true` if the password matches the hash; `false` otherwise.
   *
   * @security
   * The password is never compared directly to the hash using
   * operators like `===`. The comparison must be performed via
   * `bcrypt.compare`, which implements the appropriate verification process.
   */
  async verify(password: string, hash: string): Promise<boolean> {
    return bcrypt.compare(password, hash);
  }
}

/**
 * Singleton instance of the password service used by the application.
 *
 * @constant
 * @type {PasswordService}
 */
export default new PasswordService();
